-- SQL Schema Script for Supabase Database Initialization
-- Copy and paste this script into your Supabase SQL Editor (https://supabase.com/dashboard/project/rwiuevnywuapaqjzeubz/sql)

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. AUTHORS TABLE
CREATE TABLE IF NOT EXISTS public.authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    bio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BOOKS TABLE
CREATE TABLE IF NOT EXISTS public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author_id BIGINT REFERENCES public.authors(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    isbn TEXT,
    published_year INT,
    total_copies INT DEFAULT 1,
    available_copies INT DEFAULT 1,
    cover_image TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. MEMBERS TABLE
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. LOANS TABLE
CREATE TABLE IF NOT EXISTS public.loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    borrow_date DATE DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    return_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. USERS TABLE (Optional local profile tracking)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS for simple full-access read/write with anon key, or grant access:
ALTER TABLE public.authors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.books DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

-- SEED INITIAL DATA
INSERT INTO public.authors (name, bio) VALUES
('J.K. Rowling', 'ผู้เขียนวรรณกรรมเยาวชนชื่อดัง แฮร์รี่ พอตเตอร์'),
('George Orwell', 'นักเขียนนวนิยายแนวดิสโทเปียชื่อดัง 1984 และ Animal Farm'),
('Haruki Murakami', 'นักเขียนชาวญี่ปุ่นชื่อดังระดับโลก เจ้าของผลงาน Norwegian Wood'),
('J.R.R. Tolkien', 'ผู้สร้างจักรวาลมิดเดิลเอิร์ธ และผู้เขียน The Lord of the Rings')
ON CONFLICT DO NOTHING;

INSERT INTO public.categories (name, description) VALUES
('แฟนตาซี (Fantasy)', 'หนังสือแนวจินตนาการ เวทมนตร์ และการผจญภัย'),
('นวนิยายคลาสสิก (Classic)', 'วรรณกรรมทรงคุณค่าที่ได้รับการยอมรับระดับโลก'),
('วรรณกรรมแปล (Translation)', 'หนังสือวรรณกรรมที่แปลมาจากต่างประเทศ'),
('วิทยาศาสตร์ (Sci-Fi)', 'นวนิยายเชิงวิทยาศาสตร์และอนาคต')
ON CONFLICT DO NOTHING;

INSERT INTO public.books (title, author_id, category_id, isbn, published_year, total_copies, available_copies, cover_image, description) VALUES
('Harry Potter and the Philosopher''s Stone', 1, 1, '978-0747532699', 1997, 5, 4, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80', 'เรื่องราวการผจญภัยของแฮร์รี่ พอตเตอร์ ในโรงเรียนเวทมนตร์ฮอกวอตส์ปีแรก'),
('1984', 2, 2, '978-0451524935', 1949, 3, 2, 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80', 'นวนิยายเผด็จการแนวดิสโทเปียที่เล่าถึงเผด็จการบิ๊กบราเธอร์'),
('Norwegian Wood (ด้วยรัก ความความตาย และความทรงจำ)', 3, 3, '978-0375704024', 1987, 4, 4, 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80', 'นวนิยายความรักและความสูญเสียในวัยหนุ่มสาวช่วงทศวรรษ 1960'),
('The Hobbit', 4, 1, '978-0261102217', 1937, 6, 5, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80', 'การเดินทางผจญภัยของบิลโบ แบ็กกินส์ สู่หุบเขาเดียวดาย')
ON CONFLICT DO NOTHING;

INSERT INTO public.members (member_code, name, email, phone) VALUES
('MEM001', 'สมชาย ใจดี', 'somchai@example.com', '081-234-5678'),
('MEM002', 'สมหญิง รักเรียน', 'somying@example.com', '089-876-5432'),
('MEM003', 'กิตติพงษ์ มั่นคง', 'kittipong@example.com', '082-111-2233')
ON CONFLICT DO NOTHING;

INSERT INTO public.loans (book_id, member_id, borrow_date, due_date, return_date) VALUES
(1, 1, CURRENT_DATE - INTERVAL '5 days', CURRENT_DATE + INTERVAL '9 days', NULL),
(2, 2, CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '1 day', NULL)
ON CONFLICT DO NOTHING;
